hw4 for check
demony/DmitryKuznetsov pull request #4
Opened 2021-08-23 18:09 UTC by demony

Here we have big difference in classes structure against homework_2 and 3 homework_3. 

I change it because i was getting getting the error while tried to use listeners for making picture:
"There was an error in the forked process
invalid session id"

2021-08-27 16:21 UTC, DmitryKhodakovsky requested changes
Please resolve comments

2021-08-27 16:21 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw4/pageobjects/BaseElements.java
> +    }
This methods related to the `BasePage` but not for the `BaseElement`

2021-08-27 16:21 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw4/pageobjects/BaseElements.java
> +    public boolean closeBrowser() {
Browser should be closed only on test level

2021-08-28 19:21 UTC, demony commented on src/test/java/com/epam/tc/hw4/pageobjects/BaseElements.java
> +    }
Fixed.

2021-08-31 12:29 UTC, merged