Homework 5
demony/DmitryKuznetsov pull request #5
Opened 2021-08-29 11:52 UTC by demony

2021-08-30 13:14 UTC, komyagin requested changes

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/cucumber/context/TestContext.java
> +    private static  TestContext instance;
Two spaces

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/PropertiesForTests.java
> +        String propertyFilePath = "src//test//resources//configs//wh3-configuration.properties";
You should move the address string to the constant

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/cucumber/steps/AssertionStep.java
> +        String actualPageTitle = differentElementsPage.getTitle();
Why do you need the empty line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/cucumber/steps/AssertionStep.java
> +
Why do you need the blank line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/cucumber/steps/AssertionStep.java
> +
Why do you need the blank line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/cucumber/steps/AssertionStep.java
> +
Why do you need the blank line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/HomePage.java
> +        open("/jdi-light/index.html");
I think you should move this string to the constant

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/UserTablePage.java
> +
Why do you need the blank line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/UserTablePage.java
> +
Why do you need the blank line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +    private List<WebElement> logElements;
There are more suitable locators

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +
Why do you need the blank line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +    private boolean findAndClickOnElementContainingText(List<WebElement> webElements, String text) {
According to the "Clean code" by R.Martin and the SOLID principle you should divide this method into two methods

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +
Why do you need the blank line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +
Why do you need the blank line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/LoginComponent.java
> +        // wait.until(visibilityOf(userIcon)).click();
Why do you need commented line here?

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/LoginComponent.java
> +        // wait.until(visibilityOf(userPasswordInput)).sendKeys(text);
And here

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/LoginComponent.java
> +        // wait.until(visibilityOf(userLoginInput)).sendKeys(text);
And here

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/MenuComponent.java
> +    @FindBy(xpath = "//header//a[contains(., 'User Table ')]")
There is more suitable locator

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/components/MenuComponent.java
> +    private void findMenuElementByNameAndClickOnIt(List<WebElement> webElementList, String elementName) {
SOLID

2021-08-30 13:14 UTC, komyagin commented on src/test/java/com/epam/tc/hw5/pages/UserTablePage.java
> +    private List<WebElement> logElements;
There are more suitable locators

2021-08-30 19:40 UTC, demony commented on src/test/java/com/epam/tc/hw5/cucumber/context/TestContext.java
> +    private static  TestContext instance;
Fixed.

2021-08-30 19:40 UTC, demony commented on src/test/java/com/epam/tc/hw5/PropertiesForTests.java
> +        String propertyFilePath = "src//test//resources//configs//wh3-configuration.properties";
Fixed.

2021-08-30 19:40 UTC, demony commented on src/test/java/com/epam/tc/hw5/cucumber/steps/AssertionStep.java
> +        String actualPageTitle = differentElementsPage.getTitle();
Fixed.

2021-08-30 19:41 UTC, demony commented on src/test/java/com/epam/tc/hw5/cucumber/steps/AssertionStep.java
> +
Fixed.

2021-08-30 19:41 UTC, demony commented on src/test/java/com/epam/tc/hw5/cucumber/steps/AssertionStep.java
> +
Fixed.

2021-08-30 19:41 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/LoginComponent.java
> +        // wait.until(visibilityOf(userPasswordInput)).sendKeys(text);
Fixed.

2021-08-30 19:41 UTC, demony commented on src/test/java/com/epam/tc/hw5/cucumber/steps/AssertionStep.java
> +
Fixed.

2021-08-30 19:41 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/HomePage.java
> +        open("/jdi-light/index.html");
Fixed.

2021-08-30 19:42 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/UserTablePage.java
> +
Fixed.

2021-08-30 19:42 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/UserTablePage.java
> +
Fixed.

2021-08-30 19:42 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +    private List<WebElement> logElements;
Fixed.

2021-08-30 19:42 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +
Fixed.

2021-08-30 19:42 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +
Fixed.

2021-08-30 19:43 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/DifferentElementsComponent.java
> +
Fixed.

2021-08-30 19:43 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/LoginComponent.java
> +        // wait.until(visibilityOf(userIcon)).click();
Fixed.

2021-08-30 19:43 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/LoginComponent.java
> +        // wait.until(visibilityOf(userLoginInput)).sendKeys(text);
Fixed.

2021-08-30 19:44 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/MenuComponent.java
> +    @FindBy(xpath = "//header//a[contains(., 'User Table ')]")
Fixed.

2021-08-30 19:44 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/components/MenuComponent.java
> +    private void findMenuElementByNameAndClickOnIt(List<WebElement> webElementList, String elementName) {
Fixed.

2021-08-30 19:45 UTC, demony commented on src/test/java/com/epam/tc/hw5/pages/UserTablePage.java
> +    private List<WebElement> logElements;
Fixed. Except 
    @FindBy(css = "td:first-child")
    private List<WebElement> rowNumbers;
Can't find solution :(

2021-08-31 18:48 UTC, komyagin approved these changes

2021-08-31 18:50 UTC, merged